service: hello-api-python

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-2
  environment:
    AUTH_TOKEN: edumgt-secret-token

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  authorizer:
    handler: authorizer.authorize
    description: "TOKEN Authorizer for users REST API (oir11z21f5)"
    environment:
      AUTH_TOKEN: edumgt-secret-token
